### ISSUE TITLE
How i can install testnet only

### ISSUE THREAD

**Issue by longhoangwkm** [CounterpartyXCP/federatednode#314]
I followed this guideline https://counterparty.io/docs/federated_node/
After starting docker container, all of containers were pull. 
How can i download `bitcoin-testnet` and `counterparty-testnet` block data  only
Should i remove them in docker.yml file like this
```yml
version: '2'

services:
  bitcoin-testnet:
    extends:
      file: docker-compose.tmpl.yml
      service: bitcoin-base-testnet

  counterparty-testnet:
    extends:
      file: docker-compose.tmpl.yml
      service: counterparty-base-testnet
    links:
      - bitcoin-testnet

volumes:
  bitcoin-data:
  counterparty-data:
```
Im looking for a help.

Many thanks,
